version: '2'

services:
    hub:
        build:
            context: .
        image: esycat/jetbrains-hub
        container_name: jetbrains-hub
        restart: always
        ports:
            - 80:8080
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /data/jetbrains-hub:/var/lib/hub
            - /data/jetbrains-hub/conf:/opt/hub/conf
